In [1]:
import pandas as pd

In [3]:
# Get Dataframe from URL
url  = 'https://raw.githubusercontent.com/waldronlab/curatedMetagenomicDataCuration/master/inst/curated/LokmerA_2019/LokmerA_2019_metadata.tsv'
df = pd.read_csv(url, sep='\t')
df.head()

,study_name,sample_id,subject_id,body_site,study_condition,disease,age,age_category,gender,BMI,...,lifestyle,sequencing_platform,DNA_extraction_kit,PMID,number_reads,number_bases,minimum_read_length,median_read_length,NCBI_accession,curator
0,LokmerA_2019,SAMEA4719776,BAN01a,stool,control,healthy,62,adult,male,22.35,...,Agriculturalist,IlluminaHiSeq,Illuminakit,30726303,38631548,3901786348,101,101,ERR2619723,Arianna_Bonetti;Fatima_Zohra;Paolo_Manghi
1,LokmerA_2019,SAMEA4719777,BAN02a,stool,control,healthy,65,adult,male,20.11,...,Agriculturalist,IlluminaHiSeq,Illuminakit,30726303,43416774,4385094174,101,101,ERR2619724,Arianna_Bonetti;Fatima_Zohra;Paolo_Manghi
2,LokmerA_2019,SAMEA4719778,BAN03a,stool,control,healthy,58,adult,male,20.55,...,Agriculturalist,IlluminaHiSeq,Illuminakit,30726303,68206550,6888861550,101,101,ERR2619725,Arianna_Bonetti;Fatima_Zohra;Paolo_Manghi
3,LokmerA_2019,SAMEA4719779,BAN05a,stool,control,healthy,78,senior,male,20.92,...,Agriculturalist,IlluminaHiSeq,Illuminakit,30726303,55128218,5567950018,101,101,ERR2619726,Arianna_Bonetti;Fatima_Zohra;Paolo_Manghi
4,LokmerA_2019,SAMEA4719780,BAN07a,stool,control,healthy,56,adult,female,26.98,...,Agriculturalist,IlluminaHiSeq,Illuminakit,30726303,59833784,6043212184,101,101,ERR2619727,Arianna_Bonetti;Fatima_Zohra;Paolo_Manghi

In [4]:
keep_columns = ['NCBI_accession', 'gender', 'BMI', 'lifestyle', 'population']
df_filtered = df[keep_columns]
df_filtered.head()

  NCBI_accession  gender    BMI        lifestyle population
0     ERR2619723    male  22.35  Agriculturalist      Bantu
1     ERR2619724    male  20.11  Agriculturalist      Bantu
2     ERR2619725    male  20.55  Agriculturalist      Bantu
3     ERR2619726    male  20.92  Agriculturalist      Bantu
4     ERR2619727  female  26.98  Agriculturalist      Bantu

In [5]:
# print all NCBI_accessions
print(df_filtered['NCBI_accession'].to_string(index=False))

ERR2619723
ERR2619724
ERR2619725
ERR2619726
ERR2619727
ERR2619728
ERR2619729
ERR2619730
ERR2619731
ERR2619732
ERR2619733
ERR2619734
ERR2619735
ERR2619736
ERR2619737
ERR2619738
ERR2619739
ERR2619740
ERR2619741
ERR2619742
ERR2619743
ERR2619744
ERR2619745
ERR2619746
ERR2619747
ERR2619748
ERR2619749
ERR2619750
ERR2619751
ERR2619752
ERR2619753
ERR2619754
ERR2619755
ERR2619756
ERR2619757
ERR2619758
ERR2619759
ERR2619760
ERR2619761
ERR2619762
ERR2619763
ERR2619707
ERR2619708
ERR2619709
ERR2619710
ERR2619711
ERR2619712
ERR2619713
ERR2619714
ERR2619715
ERR2619716
ERR2619717
ERR2619718
ERR2619719
ERR2619720
ERR2619721
ERR2619722